name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie repo
      - uses: actions/checkout@v4

      # 2. Instalacja Arduino CLI
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
          arduino-cli version

      # 3. Instalacja Arduino AVR Core (UNO)
      - name: Install Arduino AVR Core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # 4. Instalacja wymaganych bibliotek
      - name: Install libraries
        run: |
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"

      # 5. Kompilacja szkicu
      - name: Compile Arduino Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ./arduino-audio-vu-meter
