name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "C:\Users\£ukasz/bin" >> 
      - name: Update cores
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      - name: Compile sketch
        run: arduino-cli compile --fqbn arduino:avr:uno ./arduino-audio-vu-meter
